# Generated by Django 6.0 on 2026-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("collector_app", "0011_collectortier_frame_key")]

    operations = [
        migrations.AlterField(
            model_name="collectortier",
            name="frame_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    'Frame given to the claimed card, as its name or its key in the Frames section ("09-20-2026", '
                    'or "09-20-2026:3" for a frame of one special). Leave empty to give whatever frame runs on the '
                    'day the card is claimed, like a catch, and write "none" for a card that always stays plain.'
                ),
                max_length=32,
            ),
        )
    ]
