# Generated by Django 6.0 on 2026-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("eventpass_app", "0013_tier_completion_message")]

    operations = [
        migrations.AlterField(
            model_name="rewardline",
            name="frame_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    'Frame given to the treasure: its name ("Haki Aura") or the key it is stored under '
                    '("09-20-2026", or "09-20-2026:3" for a frame of one special). A name is easier to read and '
                    "does not change when the event moves. Leave empty to give whatever frame runs on the day the "
                    'reward is claimed, like a catch, and write "none" for a card that always stays plain.'
                ),
                max_length=32,
            ),
        )
    ]
